REM set DBG=-Xnoagent -Djava.compiler=NONE -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=5005
set DBG=
set JLOC=c:\Users\hkim\Documents\Workspace\INTELLIJ\projectWebsites\dist
java %DBG% -classpath %JLOC%\ProjectWebsitesApp.jar org.jcvi.project_websites.utils.JsonProducer WereWolf ALL 0


REM java -classpath c:\Users\hkim\Documents\Workspace\INTELLIJ\projectWebsites\dist\ProjectWebsitesApp.jar org.jcvi.project_websites.utils.JsonProducer
"Yersinia pestis,Entamoeba histolytica,Escherichia coli,Toxoplasma gondii,Acinetobacter baumannii,Burkholderia GSC,Leptospira GSC,MRSA,Streptococcus,Aspergillus fumigatus,Aedes aegypti,Culex pipiens quinquefasciatus,Ixodes scapularis,Bacillus anthracis,Clostridium botulinum,Clostridium butyricum,Yersinia pestis MSC,Yersinia pseudotuberculosis,Burkholderia mallei,Burkholderia multivorans,Burkholderia thailandensis,Campylobacter concisus,Campylobacter curvus,Campylobacter fetus,Campylobacter hominis,Campylobacter jejuni,Clostridium perfringens,Coxiella burnetii,Entamoeba histolytica MSC,Escherichia albertii,Escherichia coli MSC,Escherichia coli O157:H7,Escherichia coli MSC,Ricinus communis,Rickettsiella grylli,Salmonella enterica,Shigella boydii,Shigella dysenteriae,Toxoplasma gondii MSC,Vibrio cholerae,Vibrio fluvialis,Vibrio harveyi,Vibrio parahaemolyticus,Vibrio,Plasmodium vivax,Bartonella bacilliformis,Borrelia afzelii,Borrelia burgdorferi,Borrelia garinii,Borrelia,Borrelia spielmanii,Borrelia valaisiana,Cryptosporidium muris,Penicillium marneffei,Streptococcus pneumoniae,Trichomonas vaginalis,Ureaplasma parvum,Ureaplasma urealyticum,Aspergillus clavatus,Bacillus cereus,Entamoeba dispar,Entamoeba invadens,Neosartorya fischeri,Pseudomonas aeruginosa,Talaromyces stipitatus"
"Organism,Category,Sample Status,Sample Name,Project Leader,Taxonomy ID,Project ID,sra accession,sra date,sra status,trace count,trace date,wgs accession,wgs date,wgs status,annotation accession,annotation date,annotation status,Project Group"
18,1,0

REM java -classpath c:\Users\hkim\Documents\Workspace\INTELLIJ\projectWebsites\dist\ProjectWebsitesApp.jar org.jcvi.project_websites.utils.JsonProducer
"Acinetobacter baumannii,Yersinia pestis,Aspergillus fumigatus,MRSA,Entamoeba histolytica,Escherichia coli,Streptococcus,Toxoplasma gondii,Borrelia,Borrelia afzelii,Borrelia burgdorferi,Borrelia garinii,Borrelia spielmanii,Borrelia valaisiana,Burkholderia mallei,Burkholderia multivorans,Campylobacter concisus,Campylobacter curvus,Campylobacter fetus,Campylobacter hominis,Campylobacter jejuni,Clostridium botulinum,Clostridium butyricum,Clostridium perfringens,Coxiella burnetii,Cryptosporidium muris,Culex pipiens quinquefasciatus,Entamoeba dispar,Entamoeba invadens,Escherichia albertii,Escherichia coli O157:H7,Ixodes scapularis,Neosartorya fischeri,Penicillium marneffei,Plasmodium vivax,Pseudomonas aeruginosa,Ricinus communis,Rickettsiella grylli,Salmonella enterica,Shigella boydii,Shigella dysenteriae,Streptococcus pneumoniae,Talaromyces stipitatus,Trichomonas vaginalis,Ureaplasma parvum,Ureaplasma urealyticum,Vibrio,Vibrio cholerae,Vibrio fluvialis,Vibrio harveyi,Vibrio parahaemolyticus,Yersinia pseudotuberculosis,Aspergillus clavatus,Bacillus anthracis,Bacillus cereus,Bartonella bacilliformis,Aedes aegypti,Entamoeba histolytica MSC,Escherichia coli MSC ,Toxoplasma gondii MSC,Yersinia pestis MSC,Burkholderia thailandensis'"
"Organism,Category,Sample Status,Sample Name,Project Leader,Taxonomy ID,Project ID,sra accession,sra date,sra status,trace count,trace date,wgs accession,wgs date,wgs status,annotation accession,annotation date,annotation status,Project Group"
18,1,0


java -classpath c:\Users\hkim\Documents\Workspace\INTELLIJ\projectWebsites\dist\ProjectWebsitesApp.jar org.jcvi.project_websites.utils.JsonProducer "Acinetobacter baumannii,Yersinia pestis,Aspergillus fumigatus,MRSA,Entamoeba histolytica,Escherichia coli,Streptococcus,Toxoplasma gondii,Borrelia,Borrelia afzelii,Borrelia burgdorferi,Borrelia garinii,Borrelia spielmanii,Borrelia valaisiana,Burkholderia mallei,Burkholderia multivorans,Campylobacter concisus,Campylobacter curvus,Campylobacter fetus,Campylobacter hominis,Campylobacter jejuni,Clostridium botulinum,Clostridium butyricum,Clostridium perfringens,Coxiella burnetii,Cryptosporidium muris,Culex pipiens quinquefasciatus,Entamoeba dispar,Entamoeba invadens,Escherichia albertii,Escherichia coli O157:H7,Ixodes scapularis,Neosartorya fischeri,Penicillium marneffei,Plasmodium vivax,Pseudomonas aeruginosa,Ricinus communis,Rickettsiella grylli,Salmonella enterica,Shigella boydii,Shigella dysenteriae,Streptococcus pneumoniae,Talaromyces stipitatus,Trichomonas vaginalis,Ureaplasma parvum,Ureaplasma urealyticum,Vibrio,Vibrio cholerae,Vibrio fluvialis,Vibrio harveyi,Vibrio parahaemolyticus,Yersinia pseudotuberculosis,Aspergillus clavatus,Bacillus anthracis,Bacillus cereus,Bartonella bacilliformis,Aedes aegypti,Entamoeba histolytica MSC,Escherichia coli MSC ,Toxoplasma gondii MSC,Yersinia pestis MSC,Burkholderia thailandensis" "Organism,Category,Sample Status,Sample Name,Project Leader,Taxonomy ID,Project ID,sra accession,sra date,sra status,trace count,trace date,wgs accession,wgs date,wgs status,annotation accession,annotation date,annotation status,Project Group" 18,1,0


java -classpath C:\Users\hkim\Documents\Workspace\INTELLIJ\projectWebsites\common\thirdparty\Servlet-2.4\*;C:\Users\hkim\Documents\Workspace\INTELLIJ\projectWebsites\common\thirdparty\Struts-2.2.1.1\*;C:\Users\hkim\Documents\Workspace\INTELLIJ\projectWebsites\common\thirdparty\JBoss-5.1.0.GA\client\*;C:\Users\hkim\Documents\Workspace\INTELLIJ\projectWebsites\common\CommonUtils\*;C:\Users\hkim\Documents\Workspace\INTELLIJ\projectWebsites\common\thirdparty\Log4J-1.2.8\*;C:\Users\hkim\Documents\Workspace\INTELLIJ\projectWebsites\common\thirdparty\JBoss-5.1.0.GA\client\*;C:\Users\hkim\Documents\Workspace\INTELLIJ\projectWebsites\common\thirdparty\JBoss-5.1.0.GA\server\*;c:\Users\hkim\Documents\Workspace\INTELLIJ\projectWebsites\dist\projectWebsites_ejb_server.jar org.jcvi.project_websites.utils.JsonProducer